"""
Django settings for WebpageMonitorBackend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Development ports and defaults
DJANGO_DEV_SERVER_PORT = 8000
FRONTEND_DEV_SERVER_PORT = 5173
POSTGRES_DEFAULT_PORT = "5432"
SMTP_DEFAULT_DEV_PORT = "25"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# FIXME: add key logic
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y!b1$Z3#^-#v@d_q&j*z&b^p@b*t*c*w*x*y*z*a*b*c*d*e*f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow local development hosts.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "pages",
    "authentication",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Whitelist the origins that are allowed to make cross-site HTTP requests.
# This is typically your frontend's address.
CORS_ALLOWED_ORIGINS = [
    f"http://localhost:{DJANGO_DEV_SERVER_PORT}",
    f"http://127.0.0.1:{DJANGO_DEV_SERVER_PORT}",
    f"http://localhost:{FRONTEND_DEV_SERVER_PORT}",  # Vite dev server
    f"http://127.0.0.1:{FRONTEND_DEV_SERVER_PORT}",
]

# Allow cookies/authorization headers to be included in cross-site requests.
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "WebpageMonitorBackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "WebpageMonitorBackend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "webpage_monitor",
        "USER": "postgres",
        "PASSWORD": "TMP_PASSWORD_",
        "HOST": "localhost",
        "PORT": POSTGRES_DEFAULT_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Media files (user-uploaded / generated artefacts)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Screenshot artefacts directory (stored on local disk)
SCREENSHOTS_DIR = BASE_DIR / "screenshots"

# Maximum number of screenshots to retain per monitored page
MAX_SCREENSHOTS_PER_PAGE = 30

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

RECENT_CHECKS_LIMIT = 10


# ---------------------------------------------------------------------------
# Logging — show INFO from app modules in the console
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        # App-level loggers — INFO and above
        "pages": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "authentication": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's own request/server logger
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Email configuration
# Defaults to the SMTP backend pointed at localhost:1025 (smtp4dev / MailHog / etc).
# Override any of these via environment variables.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
# smtp4dev default: 25   MailHog default: 1025   Papercut default: 25
# Override with the EMAIL_PORT environment variable to match your local tool.
EMAIL_PORT = int(os.getenv("EMAIL_PORT", SMTP_DEFAULT_DEV_PORT))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() in {"1", "true", "yes"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() in {"1", "true", "yes"}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmon@localhost")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# Base URL used in notification emails to build absolute links to screenshots
SITE_BASE_URL = os.getenv("SITE_BASE_URL", f"http://localhost:{DJANGO_DEV_SERVER_PORT}")
